CREATE TABLE Produtos (
Nome_Produto VARCHAR(100) NOT NULL,
ID_Produtos INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY
)

CREATE TABLE Fornecedor (
ID_Fornecedor INT AUTO_INCREMENT PRIMARY KEY PRIMARY KEY,
Razao_Social VARCHAR(100) NOT NULL
)

CREATE TABLE Item_Produto (
ID_Fornecedor INT UNIQUE,
ID_Produtos INT UNIQUE,
Quantidade INT NOT NULL,
Observacao TEXT(300),
ID_Item INT AUTO_INCREMENT PRIMARY KEY,
FOREIGN KEY(ID_Fornecedor) REFERENCES Fornecedor (ID_Fornecedor)
)

